= CSTC40 Revision 3 - kennypete keymap

An ortholinear 40% hotswap keyboard with per-key RGB in-switch LEDs and RGB Backlighting, from KP Republic.

== Revision 3: "FXTwink single pcb"

* STM32F402RCT6 MCU without separate LED driver, using `tinyuf2` bootloader. Integrated USB connection.

== Bootloader

There are three ways to enter the bootloader so that firmware can be flashed onto the keyboard:

* **Bootmagic reset** (_easiest_): Hold down the key at (0,0) in the matrix (Tab) and plug in the keyboard
* **Physical reset button**: Briefly press the button on the back of the PCB
* **Keycode in layout**: Press the keys mapped to `QK_BOOT` (0,4)+(3,4)+(3,7) in the matrix (Lower-Upper-R)

== Flashing

Once in the bootloader, the `.uf2` file produced by `qmk compile` copied to the “drive” that appears will flash the updated firmware to the keyboard.
This is an interim state, with the keymap only partially complete (but suitable for basic tasks).

== Vial

Open Vial and load the desired `.vil` file with your final, desired layers, combos, key overrides, and tap dances.

== keymap

This is a significantly re-worked keymap:

* enabling per-key RGB,
* providing much more sane default (pre-Vial) layers, and
* aligning with other `kennypete` 40% layouts and specific functionality choices.

